name: HACS and Hassfest validation

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "23 6 * * 1"

permissions:
  contents: read

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Validate integration repository with no ignored checks
        uses: hacs/action@main
        with:
          category: integration
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
